# Generated by Django 3.1.7 on 2021-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.IntegerField(blank=True, verbose_name='Количество показов')),
                ('clicks', models.IntegerField(blank=True, verbose_name='Количество кликов')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, verbose_name='Стоимость кликов в рублях')),
            ],
            options={
                'verbose_name': 'Хранилище статистики',
                'verbose_name_plural': 'Хранилище статистики',
            },
        ),
    ]
