# Generated by Django 3.1.7 on 2021-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorystatistic',
            name='clicks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='repositorystatistic',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость кликов в рублях'),
        ),
        migrations.AlterField(
            model_name='repositorystatistic',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество показов'),
        ),
    ]
