# Generated by Django 3.1.7 on 2021-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_statistic', '0002_auto_20210917_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorystatistic',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='repositorystatistic',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Стоимость кликов в рублях'),
        ),
        migrations.AlterField(
            model_name='repositorystatistic',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество показов'),
        ),
    ]
